FROM node:18.6.0-alpine3.16
RUN touch /home/node/.bashrc | echo "PS1='\w\$ '" >> /home/node/.bashrc
RUN npm config set cache /home/node/app/.npm-cache --global
COPY package*.json ./
RUN npm i -g @nestjs/cli@10.0.0
USER node
WORKDIR /home/node/app
